/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutDogsRouteImport } from './routes/_layout/dogs'
import { Route as LayoutOwnersRouteImport } from './routes/_layout/owners'
import { Route as LayoutQuestionnairesRouteImport } from './routes/_layout/questionnaires'
import { Route as LayoutRecommendationsRouteImport } from './routes/_layout/recommendations'
import { Route as LayoutSessionsRouteImport } from './routes/_layout/sessions'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutQuestionnairesQuestionnaireIdRouteImport } from './routes/_layout/questionnaires_.$questionnaireId'
import { Route as LayoutSessionsSessionIdRouteImport } from './routes/_layout/sessions_.$sessionId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDogsRoute = LayoutDogsRouteImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnersRoute = LayoutOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionnairesRoute = LayoutQuestionnairesRouteImport.update({
  id: '/questionnaires',
  path: '/questionnaires',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecommendationsRoute = LayoutRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsRoute = LayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuestionnairesQuestionnaireIdRoute =
  LayoutQuestionnairesQuestionnaireIdRouteImport.update({
    id: '/questionnaires_/$questionnaireId',
    path: '/questionnaires/$questionnaireId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSessionsSessionIdRoute = LayoutSessionsSessionIdRouteImport.update({
  id: '/sessions_/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/dogs': typeof LayoutDogsRoute
  '/owners': typeof LayoutOwnersRoute
  '/questionnaires': typeof LayoutQuestionnairesRoute
  '/recommendations': typeof LayoutRecommendationsRoute
  '/sessions': typeof LayoutSessionsRoute
  '/settings': typeof LayoutSettingsRoute
  '/questionnaires/$questionnaireId': typeof LayoutQuestionnairesQuestionnaireIdRoute
  '/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof LayoutAdminRoute
  '/dogs': typeof LayoutDogsRoute
  '/owners': typeof LayoutOwnersRoute
  '/questionnaires': typeof LayoutQuestionnairesRoute
  '/recommendations': typeof LayoutRecommendationsRoute
  '/sessions': typeof LayoutSessionsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/questionnaires/$questionnaireId': typeof LayoutQuestionnairesQuestionnaireIdRoute
  '/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/dogs': typeof LayoutDogsRoute
  '/_layout/owners': typeof LayoutOwnersRoute
  '/_layout/questionnaires': typeof LayoutQuestionnairesRoute
  '/_layout/recommendations': typeof LayoutRecommendationsRoute
  '/_layout/sessions': typeof LayoutSessionsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/questionnaires_/$questionnaireId': typeof LayoutQuestionnairesQuestionnaireIdRoute
  '/_layout/sessions_/$sessionId': typeof LayoutSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/dogs'
    | '/owners'
    | '/questionnaires'
    | '/recommendations'
    | '/sessions'
    | '/settings'
    | '/questionnaires/$questionnaireId'
    | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/admin'
    | '/dogs'
    | '/owners'
    | '/questionnaires'
    | '/recommendations'
    | '/sessions'
    | '/settings'
    | '/'
    | '/questionnaires/$questionnaireId'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/_layout/admin'
    | '/_layout/dogs'
    | '/_layout/owners'
    | '/_layout/questionnaires'
    | '/_layout/recommendations'
    | '/_layout/sessions'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/questionnaires_/$questionnaireId'
    | '/_layout/sessions_/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dogs': {
      id: '/_layout/dogs'
      path: '/dogs'
      fullPath: '/dogs'
      preLoaderRoute: typeof LayoutDogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/owners': {
      id: '/_layout/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof LayoutOwnersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/questionnaires': {
      id: '/_layout/questionnaires'
      path: '/questionnaires'
      fullPath: '/questionnaires'
      preLoaderRoute: typeof LayoutQuestionnairesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recommendations': {
      id: '/_layout/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof LayoutRecommendationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions': {
      id: '/_layout/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/questionnaires_/$questionnaireId': {
      id: '/_layout/questionnaires_/$questionnaireId'
      path: '/questionnaires/$questionnaireId'
      fullPath: '/questionnaires/$questionnaireId'
      preLoaderRoute: typeof LayoutQuestionnairesQuestionnaireIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions_/$sessionId': {
      id: '/_layout/sessions_/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof LayoutSessionsSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDogsRoute: typeof LayoutDogsRoute
  LayoutOwnersRoute: typeof LayoutOwnersRoute
  LayoutQuestionnairesRoute: typeof LayoutQuestionnairesRoute
  LayoutRecommendationsRoute: typeof LayoutRecommendationsRoute
  LayoutSessionsRoute: typeof LayoutSessionsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutQuestionnairesQuestionnaireIdRoute: typeof LayoutQuestionnairesQuestionnaireIdRoute
  LayoutSessionsSessionIdRoute: typeof LayoutSessionsSessionIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDogsRoute: LayoutDogsRoute,
  LayoutOwnersRoute: LayoutOwnersRoute,
  LayoutQuestionnairesRoute: LayoutQuestionnairesRoute,
  LayoutRecommendationsRoute: LayoutRecommendationsRoute,
  LayoutSessionsRoute: LayoutSessionsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutQuestionnairesQuestionnaireIdRoute:
    LayoutQuestionnairesQuestionnaireIdRoute,
  LayoutSessionsSessionIdRoute: LayoutSessionsSessionIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
