from sqlmodel import SQLModel

from app.models.base import CreatedAtMixin, TimestampMixin, get_datetime_utc
from app.models.dictionary import Dictionary
from app.models.dog import (
    Dog,
    DogChip,
    DogPublic,
    DogsPublic,
    DogStatus,
    Owner,
    OwnerPublic,
    OwnersPublic,
    PlacementCode,
    PlacementEvent,
    Shelter,
)
from app.models.questionnairy import (
    AnswerEvent,
    AnswerEventPublic,
    AnswerEventsPublic,
    AnswerValue,
    Question,
    QuestionPublic,
    QuestionsPublic,
    Scale,
    ScaleConfig,
    ScaleType,
    SessionAnswerPublic,
    SessionAnswersPublic,
    SessionStatus,
    Survey,
    SurveyPublic,
    SurveyQuestion,
    SurveyQuestionGroup,
    SurveySession,
    SurveySessionPublic,
    SurveySessionsPublic,
    SurveysPublic,
    SurveyVersion,
    SurveyVersionPublic,
    SurveyVersionsPublic,
)
from app.models.recommendation import (
    Recommendation,
    RecommendationGroup,
    RecommendationPublic,
    RecommendationsPublic,
    SessionRecommendation,
    SessionRecommendationItemPublic,
    SessionRecommendationItemsPublic,
    SessionRecommendationPublic,
    SessionRecommendationsPublic,
)
from app.models.user import (
    Consent,
    Message,
    Token,
    TokenPayload,
    UpdatePassword,
    User,
    UserCreate,
    UserGroup,
    UserPublic,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
)

__all__ = [
    "AnswerEvent",
    "AnswerEventPublic",
    "AnswerEventsPublic",
    "AnswerValue",
    "Consent",
    "CreatedAtMixin",
    "Dictionary",
    "Dog",
    "DogChip",
    "DogPublic",
    "DogsPublic",
    "DogStatus",
    "Owner",
    "OwnerPublic",
    "OwnersPublic",
    "Message",
    "PlacementCode",
    "PlacementEvent",
    "Question",
    "QuestionPublic",
    "QuestionsPublic",
    "Survey",
    "SurveyPublic",
    "SurveyQuestion",
    "SurveyQuestionGroup",
    "SurveySession",
    "SurveySessionPublic",
    "SurveySessionsPublic",
    "SurveyVersion",
    "SurveyVersionPublic",
    "SurveyVersionsPublic",
    "SurveysPublic",
    "SessionAnswerPublic",
    "SessionAnswersPublic",
    "Recommendation",
    "RecommendationGroup",
    "RecommendationPublic",
    "RecommendationsPublic",
    "SessionRecommendation",
    "SessionRecommendationItemPublic",
    "SessionRecommendationItemsPublic",
    "SessionRecommendationPublic",
    "SessionRecommendationsPublic",
    "SQLModel",
    "Scale",
    "ScaleConfig",
    "ScaleType",
    "SessionStatus",
    "Shelter",
    "TimestampMixin",
    "Token",
    "TokenPayload",
    "UpdatePassword",
    "User",
    "UserCreate",
    "UserGroup",
    "UserPublic",
    "UserUpdate",
    "UserUpdateMe",
    "UsersPublic",
    "get_datetime_utc",
]

# Register SQLAlchemy session guards after all model classes are loaded.
from app.models import catalog_immutability as _catalog_immutability  # noqa: E402,F401
