// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AdminContourStub
 */
export type AdminContourStub = {
    /**
     * Contour
     */
    contour?: string;
    /**
     * Status
     */
    status?: string;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DogPublic
 */
export type DogPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Sex
     */
    sex?: string | null;
    /**
     * Neutered
     */
    neutered?: boolean | null;
    /**
     * Status
     */
    status: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Shelter Id
     */
    shelter_id?: string | null;
    /**
     * Assigned Volunteer Id
     */
    assigned_volunteer_id?: string | null;
    /**
     * Owner Id
     */
    owner_id?: string | null;
    /**
     * Birthday
     */
    birthday?: string | null;
    /**
     * Adopted At
     */
    adopted_at?: string | null;
    /**
     * Breed
     */
    breed?: string | null;
    /**
     * Mixed
     */
    mixed?: boolean | null;
    /**
     * Created By Id
     */
    created_by_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DogsPublic
 */
export type DogsPublic = {
    /**
     * Data
     */
    data: Array<DogPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OwnerPublic
 */
export type OwnerPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Contact
     */
    contact?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * OwnersPublic
 */
export type OwnersPublic = {
    /**
     * Data
     */
    data: Array<OwnerPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * QuestionPublic
 */
export type QuestionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Questionnaire Id
     */
    questionnaire_id: string;
    /**
     * Global Id
     */
    global_id: string;
    /**
     * Order Number
     */
    order_number: number;
    /**
     * Text
     */
    text: string;
    /**
     * Scale Id
     */
    scale_id: string;
    /**
     * Scale Name
     */
    scale_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * QuestionnairePublic
 */
export type QuestionnairePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * QuestionnaireSessionPublic
 */
export type QuestionnaireSessionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Dog Id
     */
    dog_id: string;
    /**
     * Questionnaire Id
     */
    questionnaire_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Client Metadata
     */
    client_metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * QuestionnaireSessionsPublic
 */
export type QuestionnaireSessionsPublic = {
    /**
     * Data
     */
    data: Array<QuestionnaireSessionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * QuestionnairesPublic
 */
export type QuestionnairesPublic = {
    /**
     * Data
     */
    data: Array<QuestionnairePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * QuestionsPublic
 */
export type QuestionsPublic = {
    /**
     * Data
     */
    data: Array<QuestionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * RecommendationPublic
 */
export type RecommendationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Text
     */
    text: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RecommendationsPublic
 */
export type RecommendationsPublic = {
    /**
     * Data
     */
    data: Array<RecommendationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * SessionAnswerPublic
 */
export type SessionAnswerPublic = {
    /**
     * Question Id
     */
    question_id: string;
    /**
     * Order Number
     */
    order_number: number;
    /**
     * Question Text
     */
    question_text: string;
    /**
     * Value Num
     */
    value_num?: string | null;
    /**
     * Value Text
     */
    value_text?: string | null;
    /**
     * Value Date
     */
    value_date?: string | null;
    /**
     * Answered At
     */
    answered_at?: string | null;
};

/**
 * SessionAnswersPublic
 */
export type SessionAnswersPublic = {
    /**
     * Data
     */
    data: Array<SessionAnswerPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * SessionRecommendationItemPublic
 */
export type SessionRecommendationItemPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Recomendation Id
     */
    recomendation_id: string;
    /**
     * Chart Number
     */
    chart_number: number;
    /**
     * Weight
     */
    weight: number;
    /**
     * Comment
     */
    comment?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Recommendation Name
     */
    recommendation_name: string;
    /**
     * Recommendation Slug
     */
    recommendation_slug: string;
    /**
     * Recommendation Text
     */
    recommendation_text: string;
};

/**
 * SessionRecommendationItemsPublic
 */
export type SessionRecommendationItemsPublic = {
    /**
     * Data
     */
    data: Array<SessionRecommendationItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Group
     */
    group?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Contact
     */
    contact?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Group
     */
    group?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Contact
     */
    contact?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Group
     */
    group?: string | null;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Contact
     */
    contact?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Email
         */
        email?: string | null;
        /**
         * Full Name
         */
        full_name?: string | null;
        /**
         * Is Superuser
         */
        is_superuser?: boolean | null;
        /**
         * Is Active
         */
        is_active?: boolean | null;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type dogsReadDogsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Name
         */
        name?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Shelter Id
         */
        shelter_id?: string | null;
        /**
         * Owner Id
         */
        owner_id?: string | null;
    };
    url: '/api/v1/dogs/';
};

export type dogsReadDogsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dogsReadDogsError = dogsReadDogsErrors[keyof dogsReadDogsErrors];

export type dogsReadDogsResponses = {
    /**
     * Successful Response
     */
    200: DogsPublic;
};

export type dogsReadDogsResponse = dogsReadDogsResponses[keyof dogsReadDogsResponses];

export type ownersReadOwnersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Name
         */
        name?: string | null;
        /**
         * Email
         */
        email?: string | null;
        /**
         * Phone
         */
        phone?: string | null;
    };
    url: '/api/v1/owners/';
};

export type ownersReadOwnersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type ownersReadOwnersError = ownersReadOwnersErrors[keyof ownersReadOwnersErrors];

export type ownersReadOwnersResponses = {
    /**
     * Successful Response
     */
    200: OwnersPublic;
};

export type ownersReadOwnersResponse = ownersReadOwnersResponses[keyof ownersReadOwnersResponses];

export type questionnairesReadQuestionnairesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Name
         */
        name?: string | null;
        /**
         * Slug
         */
        slug?: string | null;
    };
    url: '/api/v1/questionnaires/';
};

export type questionnairesReadQuestionnairesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionnairesReadQuestionnairesError = questionnairesReadQuestionnairesErrors[keyof questionnairesReadQuestionnairesErrors];

export type questionnairesReadQuestionnairesResponses = {
    /**
     * Successful Response
     */
    200: QuestionnairesPublic;
};

export type questionnairesReadQuestionnairesResponse = questionnairesReadQuestionnairesResponses[keyof questionnairesReadQuestionnairesResponses];

export type questionnairesReadQuestionnaireData = {
    body?: never;
    path: {
        /**
         * Questionnaire Id
         */
        questionnaire_id: string;
    };
    query?: never;
    url: '/api/v1/questionnaires/{questionnaire_id}';
};

export type questionnairesReadQuestionnaireErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionnairesReadQuestionnaireError = questionnairesReadQuestionnaireErrors[keyof questionnairesReadQuestionnaireErrors];

export type questionnairesReadQuestionnaireResponses = {
    /**
     * Successful Response
     */
    200: QuestionnairePublic;
};

export type questionnairesReadQuestionnaireResponse = questionnairesReadQuestionnaireResponses[keyof questionnairesReadQuestionnaireResponses];

export type questionnairesReadQuestionnaireQuestionsData = {
    body?: never;
    path: {
        /**
         * Questionnaire Id
         */
        questionnaire_id: string;
    };
    query?: never;
    url: '/api/v1/questionnaires/{questionnaire_id}/questions';
};

export type questionnairesReadQuestionnaireQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type questionnairesReadQuestionnaireQuestionsError = questionnairesReadQuestionnaireQuestionsErrors[keyof questionnairesReadQuestionnaireQuestionsErrors];

export type questionnairesReadQuestionnaireQuestionsResponses = {
    /**
     * Successful Response
     */
    200: QuestionsPublic;
};

export type questionnairesReadQuestionnaireQuestionsResponse = questionnairesReadQuestionnaireQuestionsResponses[keyof questionnairesReadQuestionnaireQuestionsResponses];

export type sessionsReadQuestionnaireSessionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: string | null;
        /**
         * User Id
         */
        user_id?: string | null;
        /**
         * Dog Id
         */
        dog_id?: string | null;
        /**
         * Questionnaire Id
         */
        questionnaire_id?: string | null;
    };
    url: '/api/v1/questionnaire-sessions/';
};

export type sessionsReadQuestionnaireSessionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type sessionsReadQuestionnaireSessionsError = sessionsReadQuestionnaireSessionsErrors[keyof sessionsReadQuestionnaireSessionsErrors];

export type sessionsReadQuestionnaireSessionsResponses = {
    /**
     * Successful Response
     */
    200: QuestionnaireSessionsPublic;
};

export type sessionsReadQuestionnaireSessionsResponse = sessionsReadQuestionnaireSessionsResponses[keyof sessionsReadQuestionnaireSessionsResponses];

export type sessionsReadQuestionnaireSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/questionnaire-sessions/{session_id}';
};

export type sessionsReadQuestionnaireSessionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type sessionsReadQuestionnaireSessionError = sessionsReadQuestionnaireSessionErrors[keyof sessionsReadQuestionnaireSessionErrors];

export type sessionsReadQuestionnaireSessionResponses = {
    /**
     * Successful Response
     */
    200: QuestionnaireSessionPublic;
};

export type sessionsReadQuestionnaireSessionResponse = sessionsReadQuestionnaireSessionResponses[keyof sessionsReadQuestionnaireSessionResponses];

export type sessionsReadQuestionnaireSessionAnswersData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/questionnaire-sessions/{session_id}/answers';
};

export type sessionsReadQuestionnaireSessionAnswersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type sessionsReadQuestionnaireSessionAnswersError = sessionsReadQuestionnaireSessionAnswersErrors[keyof sessionsReadQuestionnaireSessionAnswersErrors];

export type sessionsReadQuestionnaireSessionAnswersResponses = {
    /**
     * Successful Response
     */
    200: SessionAnswersPublic;
};

export type sessionsReadQuestionnaireSessionAnswersResponse = sessionsReadQuestionnaireSessionAnswersResponses[keyof sessionsReadQuestionnaireSessionAnswersResponses];

export type sessionsReadQuestionnaireSessionRecommendationsData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/questionnaire-sessions/{session_id}/recommendations';
};

export type sessionsReadQuestionnaireSessionRecommendationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type sessionsReadQuestionnaireSessionRecommendationsError = sessionsReadQuestionnaireSessionRecommendationsErrors[keyof sessionsReadQuestionnaireSessionRecommendationsErrors];

export type sessionsReadQuestionnaireSessionRecommendationsResponses = {
    /**
     * Successful Response
     */
    200: SessionRecommendationItemsPublic;
};

export type sessionsReadQuestionnaireSessionRecommendationsResponse = sessionsReadQuestionnaireSessionRecommendationsResponses[keyof sessionsReadQuestionnaireSessionRecommendationsResponses];

export type recommendationsReadRecommendationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Name
         */
        name?: string | null;
        /**
         * Slug
         */
        slug?: string | null;
    };
    url: '/api/v1/recommendations/';
};

export type recommendationsReadRecommendationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type recommendationsReadRecommendationsError = recommendationsReadRecommendationsErrors[keyof recommendationsReadRecommendationsErrors];

export type recommendationsReadRecommendationsResponses = {
    /**
     * Successful Response
     */
    200: RecommendationsPublic;
};

export type recommendationsReadRecommendationsResponse = recommendationsReadRecommendationsResponses[keyof recommendationsReadRecommendationsResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type adminAdminContourStubData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/';
};

export type adminAdminContourStubResponses = {
    /**
     * Successful Response
     */
    200: AdminContourStub;
};

export type adminAdminContourStubResponse = adminAdminContourStubResponses[keyof adminAdminContourStubResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
